// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("tae_exam_candidate_kp")>]
[<assembly: AssemblyProductAttribute("tae_exam_candidate_kp")>]
[<assembly: AssemblyDescriptionAttribute("Demonstration sample of test automation for Test Automation Engineer position")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "tae_exam_candidate_kp"
    let [<Literal>] AssemblyProduct = "tae_exam_candidate_kp"
    let [<Literal>] AssemblyDescription = "Demonstration sample of test automation for Test Automation Engineer position"
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
    let [<Literal>] AssemblyConfiguration = "Release"
